[workspace]
members = [ 
    "constants",
    "stages/first_stage",
    "stages/second_stage",
    "cpu_utils",
    "kernel",
]
resolver = "2"

[profile.release]
opt-level = 's'
overflow-checks = false
