[package]
name = "RustOS"
version = "0.1.0"
edition = "2021"

# The panic = "abort" disables unwinding 
# Stack unwinding means that when the program panics, all alive stack members are freed from memory
[features]
default = ["16bit", "32bit"]
16bit = []
32bit = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
