[package]
name = "RustOS"
version = "0.1.0"
edition = "2021"

[build]
target = "i386-code16-boot-sector.json"

# The panic = "abort" disables unwinding 
# Stack unwinding means that when the program panics, all alive stack members are freed from memory
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
