[package]
edition = "2024"
name = "second_stage"
version = "0.1.0"

[dependencies]
common = { path = "../../common", features = ["structures", "constants"] }
cpu_utils = { path = "../../cpu_utils", features = [
    "paging",
    "global_descriptor_table",
] }

[profile.release]
opt-level = 0
