[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
constants = { path = "../constants" }
utils = { path = "../utils", features = ["screen", "paging", "allocator", "global_descriptor_table"]}