[package]
edition = "2024"
name = "first_stage"
version = "0.1.0"

[dependencies]
constants = { path = "../../constants" }
cpu_utils = { path = "../../cpu_utils", features = [
    "global_descriptor_table",
    "master_boot_record",
] }
