[package]
edition = "2024"
name = "second_stage"
version = "0.1.0"

[dependencies]
common = { path = "../../../shared/common", features = ["second_stage"] }
cpu_utils = { path = "../../../shared/cpu_utils", features = [
    "paging",
    "global_descriptor_table",
] }
